# Generated by Django 4.2.4 on 2023-10-05 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Įveskite serviso darbuotojo varda ir pavarde', max_length=100, verbose_name='Autoserviso darbuotojas')),
            ],
        ),
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=100, verbose_name='Automobilio marke ir modelis')),
                ('year', models.DateTimeField()),
                ('plate', models.CharField(max_length=10, verbose_name='Automobilio numeriai')),
                ('vin', models.CharField(max_length=17, verbose_name='Automobilio VIN kodas')),
                ('failure', models.TextField(help_text='Trumpas gedimu aprasymas', max_length=1000, verbose_name='Automobilio gedimo aprasymas')),
                ('mechanic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.mechanic')),
            ],
        ),
    ]
