# Generated by Django 4.2.4 on 2023-10-05 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinfo',
            old_name='year',
            new_name='manufacture_year',
        ),
        migrations.AddField(
            model_name='carinfo',
            name='engine',
            field=models.CharField(default=django.utils.timezone.now, help_text='Automobilio darbinis turis cm3', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carinfo',
            name='fuel_type',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('gas', 'Gas'), ('electric', 'Electric')], default='Petrol', max_length=8),
        ),
    ]
