# Generated by Django 4.2.4 on 2023-10-09 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_carinfo_manufacture_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=20, verbose_name='Automobilio savininko vardas')),
                ('owner_surname', models.CharField(max_length=20, verbose_name='Automobilio savininko pavarde')),
                ('owner_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.carinfo')),
            ],
        ),
    ]
