# Generated by Django 4.2.4 on 2023-10-09 19:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unikalus ID kiekvienam automobiliui', primary_key=True, serialize=False)),
                ('due_finish', models.DateField(blank=True, null=True, verbose_name='Automobilis planuojamas suremontuoti')),
                ('status', models.CharField(blank=True, choices=[('w', 'Laukia darbų pradžios'), ('i', 'Vyksta automobilio inspektavimas'), ('r', 'Remontuojamas automobilis'), ('f', 'Automobilis suremontuotas')], default='w', help_text='Statusas', max_length=1)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.carinfo')),
            ],
            options={
                'ordering': ['due_finish'],
            },
        ),
    ]
