# Generated by Django 4.2.4 on 2023-10-09 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_carstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='car_image',
            field=models.ImageField(null=True, upload_to='cars', verbose_name='Car image'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='mechanic',
            field=models.ForeignKey(help_text='Serviso darbuotojas atliekantis darbus', null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.mechanic'),
        ),
    ]
