# Generated by Django 4.2.4 on 2023-10-10 09:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=100, verbose_name='Automobilio markė ir modelis')),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('gas', 'Gas'), ('electric', 'Electric')], default='Petrol', max_length=8)),
                ('engine', models.CharField(help_text='Automobilio darbinis turis cm3', max_length=4)),
                ('manufacture_year', models.DateField()),
                ('plate', models.CharField(max_length=10, verbose_name='Automobilio numeriai')),
                ('vin', models.CharField(max_length=17, verbose_name='Automobilio VIN kodas')),
                ('summary', models.TextField(help_text='Trumpas gedimu aprasymas', max_length=1000, verbose_name='Automobilio gedimo aprasymas')),
                ('car_image', models.ImageField(null=True, upload_to='cars', verbose_name='Car image')),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Įveskite serviso darbuotojo vardą ir pavardę', max_length=100, verbose_name='Autoserviso darbuotojas')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Automobilio savininko vardas')),
                ('surname', models.CharField(max_length=20, verbose_name='Automobilio savininko pavarde')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.carinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CarStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unikalus ID kiekvienam automobiliui', primary_key=True, serialize=False)),
                ('due_finish', models.DateField(blank=True, null=True, verbose_name='Automobilis planuojamas suremontuoti')),
                ('status', models.CharField(blank=True, choices=[('w', 'Laukia darbų pradžios'), ('i', 'Vyksta automobilio inspektavimas'), ('r', 'Remontuojamas automobilis'), ('f', 'Automobilis suremontuotas')], default='w', help_text='Statusas', max_length=1)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.carinfo')),
            ],
            options={
                'ordering': ['due_finish'],
            },
        ),
        migrations.AddField(
            model_name='carinfo',
            name='car_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.owner'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='mechanic',
            field=models.ForeignKey(help_text='Serviso darbuotojas atliekantis darbus', null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.mechanic'),
        ),
    ]
