# Generated by Django 4.2.4 on 2023-10-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='cars', verbose_name='Car image'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.owner'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.carinfo'),
        ),
    ]
