# Generated by Django 4.2.4 on 2023-10-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_alter_carinfo_car_image_alter_carinfo_car_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mechanic',
            options={'verbose_name': 'Mechanikas', 'verbose_name_plural': 'Mechanikai'},
        ),
    ]
