# Generated by Django 4.2.4 on 2023-10-10 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_alter_mechanic_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='car_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='autoservice.owner'),
        ),
    ]
