# Generated by Django 4.2.4 on 2023-10-11 09:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0005_carstatus_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='description',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
